# 开发环境配置
elasticsearch:
  host: localhost
  port: 9200
  username: 
  password: 
  connection-timeout: 10s
  socket-timeout: 30s

# 日志配置
logging:
  level:
    root: info
    cloud.catfish: debug
    org.springframework.data.elasticsearch: debug
    org.elasticsearch.client: debug