spring:
  config:
    import:
      - classpath:config/dev/database.yml
      - classpath:config/dev/redis.yml
      - classpath:config/dev/minio.yml
      - classpath:config/dev/elasticsearch.yml
      - classpath:config/dev/websocket.yml
      - classpath:config/dev/logging.yml
