spring:
  config:
    import:
      - classpath:config/prod/database.yml
      - classpath:config/prod/redis.yml
      - classpath:config/prod/minio.yml
      - classpath:config/prod/elasticsearch.yml
      - classpath:config/prod/websocket.yml
      - classpath:config/prod/logging.yml
